language: python

python:
  - "2.7"

env:
  - DJANGO=Django==1.4.10
  - DJANGO=Django==1.6
  - DJANGO=Django==1.7

install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -e .

script: python setup.py test
